### ISSUE TITLE
rax-picture 图片类型可能判断错误导致压缩失败

### ISSUE THREAD

**Issue by locknono** [raxjs/rax-components#107]
https://github.com/raxjs/rax-components/blob/81ba2d3e956257dab1870641e60657a7220e246c/packages/rax-picture/src/optimizer/index.ts#L52

为什么用 indexOf('gif') 来判断是不是 GIF ，而不是用后缀 ？可能判断错误导致无法压缩？

**Comment by wssgcg1213** [comment]
url 末尾可能带 query, 可以用 `/\.gif($|\?)/i.test`
