### ISSUE TITLE
rax-text组件设置ref无效

### ISSUE THREAD

**Issue by jokeuncle** [raxjs/rax-components#109]
##### 首先利用forwardRef转发ref
```javascript
const Tag = forwardRef((props, ref) => {
  ...other code
  return icon ? <View className="icon-tag" ref={ref}  style={style}></View> : text ? <Text className="text-tag" ref={ref} style={style}>{text}</Text> : '';
});
export default Tag;
```

##### 创建ref
```javascript
export default function (props) {
  const { itemData={}, last } = props;
  const { pictureUrl, title } = itemData;
  const iconTag = createRef();
  window.iconTag = iconTag;
  return (
    <View className="one-row-one-column" style={{marginBottom: last ? 0 : 18}}>
      {/*商品图片*/}
      <Avatar uri={pictureUrl} width={defaultWidthFor1_1ItemAvatar} height={defaultHeightFor1_1ItemAvatar}/>
      <View className="item-detail">
        {/*标题*/}
        <ItemTitle className="title-row" title={title} width={defaultTitleWidthFor1_1Item} tag={iconTag}><Tag ref={iconTag} type={"E_COUPON"}/></ItemTitle>
        {/*特点描述*/}
        <Feature className="feature-row" type={"HOT"} text={"这个当季最好"}/>
        {/*文本标*/}
        <View className="tag-row"><Tag text={"满3件减10元"}/></View>
      </View>
    </View>
  );
}
```

##### 打印window.iconTag
{current: null}

##### 但是将Tag的实现由Text转向View后，再复现上述过程，是可以的，View设置ref有效
{current: div}

**Comment by fyangstudio** [comment]
使用 useRef 创建 ref 。
详见：https://rax.js.org/docs/api/useref

**Comment by jokeuncle** [comment]
> ```js-jsx
> import { createElement, createRef, useEffect } from 'rax';
> import Text from 'rax-text';
> 
> export default (props) => {
>   const testRef = createRef();
> 
>   useEffect(() => {
>     console.log(testRef.current);
>   }, []);
> 
>   return <Text ref={testRef}>Hello</Text>;
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/9896768/72408962-585c6780-379f-11ea-8c0f-daeb4561edd1.png)
> 
> 可以获取 current， rax-text 的版本是多少？

你试试forward Ref，这两种场景也许仍有细分区别，rax-text版本1.0.2。使用useRef过后，在forwardRef场景下仍然无效。
![image](https://user-images.githubusercontent.com/18191098/72409203-08ca6b80-37a0-11ea-93d1-a2402553e41d.png)
![image](https://user-images.githubusercontent.com/18191098/72409226-12ec6a00-37a0-11ea-8769-37c3277682f6.png)

**Comment by fyangstudio** [comment]
```jsx
// Test.jsx
import { createElement, forwardRef } from 'rax';
import Text from 'rax-text';

function Test(props, ref) {
  return <Text ref={ref}>Test</Text>;
};

export default forwardRef(Test);
```

```jsx
// index.jsx
import { createElement, createRef, useEffect } from 'rax';
import Test from './Test';

export default (props) => {
  const testRef = createRef();

  useEffect(() => {
    console.log(testRef.current);
  }, []);

  return <Test ref={testRef} />;
};
```
![image](https://user-images.githubusercontent.com/9896768/72409770-ac684b80-37a1-11ea-810c-5384bf7d6327.png)

**Comment by jokeuncle** [comment]
> ```js-jsx
> // Test.jsx
> import { createElement, forwardRef } from 'rax';
> import Text from 'rax-text';
> 
> function Test(props, ref) {
>   return <Text ref={ref}>Test</Text>;
> };
> 
> export default forwardRef(Test);
> ```
> 
> ```js-jsx
> // index.jsx
> import { createElement, createRef, useEffect } from 'rax';
> import Test from './Test';
> 
> export default (props) => {
>   const testRef = createRef();
> 
>   useEffect(() => {
>     console.log(testRef.current);
>   }, []);
> 
>   return <Test ref={testRef} />;
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/9896768/72409770-ac684b80-37a1-11ea-810c-5384bf7d6327.png)

![image](https://user-images.githubusercontent.com/18191098/72410235-e554f000-37a2-11ea-96ac-35b28906eb9b.png)

可能是环境不一致，我这边还是不行。 不过辛苦💦感谢了～
