### ISSUE TITLE
Rax ScrollView Web component scroll bars issue

### ISSUE THREAD

**Issue by dab77** [raxjs/rax-components#126]
Inner container style of ScrollView for web has "overflow: scroll". So it display scroll bars for all directions. 

May be better use "overflow: auto", or for horizontal mode set to "overflow-x: scroll", and for vertical mode - "overflow-y: scroll"

https://github.com/raxjs/rax-components/blob/master/packages/rax-scrollview/src/index.tsx

![FD36AFD3-D14A-457E-850B-A7DF192E8843](https://user-images.githubusercontent.com/44308247/74351570-56022300-4dc8-11ea-924d-b2ec0f8a18f3.png)

**Comment by lybeen** [comment]
thx，i will fix later

**Comment by SoloJiang** [comment]
#130
