### ISSUE TITLE
rax-slider在微信小程序和支付宝小程序中不起作用

### ISSUE THREAD

**Issue by zhugexiansheng** [raxjs/rax-components#142]
rax-slider在微信小程序中用不了，应该是wxml里面的<slot>需要改成支持多个slot插入的方式，同理在支付宝小程序中也是一样，需要将slot改成swiper-item的方式接入
需要将
```jsx
<slot>
```
改为
```jsx
<swiper-item wx:for="{{tabs}}" wx:key="index">
    <slot name="tab-content-{{index}}"></slot>
 </swiper-item>
```

同时在微信小程序的js文件中需要支持多个slot接入的方式
```
options: {
    multipleSlots: true
 },
```

**Comment by SoloJiang** [comment]
如果用多 slot 的话，会导致在使用的时候开发者必须要在 item 上写 `slot="xxxx"` 这样的代码，在多端用户体验上存在一些问题，所以已经计划使用编译时来实现这个组件，本周完成~
