### ISSUE TITLE
QRCode 组件的样式宽度和高度应该接受 px/rpx 为单位

### ISSUE THREAD

**Issue by wssgcg1213** [raxjs/rax-components#166]
https://github.com/raxjs/rax-components/blob/master/packages/rax-qrcode/src/index.tsx#L41

默认 README 里面的数字, 看起来是 rpx 为标准的, 但是又会生成一个 width/height 的属性给 canvas

```
<QRCode style={{ width: 400, height: 400 }} />

->

<canvas width="400" height="400" style="width: 53.3333vw; height: 53.3333vw" />
```

这里两个尺寸是冲突的

**Comment by SoloJiang** [comment]
https://github.com/raxjs/rax-components/pull/176

**Comment by Tanelmer** [comment]
现象：支付宝小程序中，使用qrcode组件，设置styles的width，height时，安卓高分辨率机型有兼容问题，二维码宽高异常。
原因：my.getSystemInfoSync().screenWidth !== my.getSystemInfoSync().windowWidth ，screenWidth = 1080，windowWidth=360
code：`<QRCode className="qrcode" style={{ width: '400rpx', height: '400rpx' }} data={'123456789'} />`
