### ISSUE TITLE
rax-text don't crop lines for H5

### ISSUE THREAD

**Issue by dab77** [raxjs/rax-components#170]
On H5, property "numberOfLines" don't crop lines if >=2 and does not add a tree dots at the end of the line.

**Comment by fyangstudio** [comment]
@yacheng 和同学反馈的是同一个问题吗

**Comment by yacheng** [comment]
numberOfLines  的支持参考这个例子 https://codepen.io/yacheng_sz/pen/XWbBVJY?editors=0010
是支持 numberOfLines=2 的

**Comment by dab77** [comment]
sorry, we use old version
