### ISSUE TITLE
rax-scrollview for H5, property "showsHorizontalScrollIndicator" not work correctly

### ISSUE THREAD

**Issue by dab77** [raxjs/rax-components#171]
Setting property "showsHorizontalScrollIndicator=false" still show scroll bar on h5

**Comment by SoloJiang** [comment]
可以看下是否给 `rax-scrollview` 设置了指定的宽度

**Comment by valkurash** [comment]
> 可以看下是否给 `rax-scrollview` 设置了指定的宽度

Width is not set explicitly, it depends on parent width. I think problem is in adding inline styles, because  it is not set class properly
```<style id="rax-scrollview-style">.undefined::-webkit-scrollbar{display: none;}</style>```

**Comment by valkurash** [comment]
https://campaign.aliexpress.com/wow/gf/upr-main?wh_pid=2YxsE2zIgN&wh_weex=true&preDownLoad=true&preInitInstance=rax

Example page, even with manually set styles by me in header it did not work

**Comment by fyangstudio** [comment]
#201

**Comment by fyangstudio** [comment]
fixed
