### ISSUE TITLE
rax-pwa 从 rax 仓库中抽离

### ISSUE THREAD

**Issue by boiawang** [raxjs/rax-components#194]
目前 [rax-pwa](https://github.com/alibaba/rax/tree/master/packages/rax-pwa) 作为组件放在 rax 仓库下不合适，建议拆出 rax-tabbar 和 rax-navigation 组件到 rax-components 或者 rax-ui 下，需要看下这两个算不算基础组件。

**Comment by boiawang** [comment]
@SoloJiang @imsobear @fyangstudio  看下

**Comment by fyangstudio** [comment]
可以迁移到 rax-components

**Comment by fyangstudio** [comment]
[https://github.com/alibaba/rax/pull/1880](https://github.com/alibaba/rax/pull/1880)

**Comment by fyangstudio** [comment]
应该是2个事情：
一个是修复当前用户遇到的问题，已修复 PR:  https://github.com/alibaba/rax/pull/1880
一个是 rax-tabbar 和 rax-navigation 何去何从。

当前 rax-tabbar 和 rax-navigation 有大量 rax-app 耦合的定制逻辑，之前的设计思路是用户通过配置生成对应工程表现，用户并不用关心用到了什么组件。 
他们虽然是组件但不是基础组件，是包含项目属性的组件，同时在已经通过 app config 生成后，再手动引入会对项目产生一定的影响。

PWA 作为综合解决方案，包含构建时，运行时及组件，应该也算合理
