### ISSUE TITLE
Icon 组件在支付宝小程序下自定义 style 无效

### ISSUE THREAD

**Issue by taberh** [raxjs/rax-components#215]
<Icon style={{fontSize: '20rpx'}} />

在使用 Icon 组件时，自定义 style 在支付宝小程序下将被丢失

https://github.com/raxjs/rax-components/blob/master/packages/rax-icon/src/miniapp/index.ts#L51

这里的 style 应该是个 string

**Comment by chenjun1011** [comment]
fixed in https://github.com/raxjs/rax-components/pull/226
