### ISSUE TITLE
rax-waterfall nimiapp 调用死循环

### ISSUE THREAD

**Issue by shiying** [raxjs/rax-components#238]
https://github.com/raxjs/rax-components/blob/master/packages/rax-waterfall/src/miniapp/index.ts

 didUpdate: function didUpdate() {
    this.update();
  },

update() {
      let columns = this.getColunms(this.props.dataSource, this.props.columnCount);
      this.setData({ columns });
    },

**Comment by ChrisCindy** [comment]
waterfall 不支持小程序端
