### ISSUE TITLE
Bug： rax-tab-panel ,  tab not align center 

### ISSUE THREAD

**Issue by michaeldong** [raxjs/rax-components#242]
Envrionment: Android Weex Playground
Weex SDK version : 0.24.0
Demo Code: rax-tab-panel demo 

`
<TabController
          isPanEnabled={true}
          isSlideEnabled={true}
          style={styles.tabBar}
          ref={this.tabBar}
          beforeSwitch={this.beforeTabBarSwitch}
          afterSwitch={this.afterTabBarSwitch}
          defaultFocusIndex={0}
          useSlider={true}
        >

          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
          <TabPanel style={styles.page}>
            <TabPanelView style={{ flex: 1 }}>{1}</TabPanelView>
          </TabPanel>
        </TabController>
`

When you scroll TabController, Tab‘s  current  Select Index  change.  But the  "block" transition not right.  the selected tab not align center.  100% occur. when you scroll ten or more times.  Maybe reason is this code.

`
    transition(
      block,
      {
        transform: `translateX(${left}rpx)`,
        webkitTransform: `translateX(${left}rpx)`,
        width: `${itemWidth}rpx`
      },
      {
        timingFunction: 'ease-out',
        delay: 0,
        duration: 200
      },
      () => {
        afterSwitch({
          index,
          type
        });
      }
    );
`

**Comment by SoloJiang** [comment]
@recover758126 will see it later

**Comment by recover758126** [comment]
I will fix this bug recently

**Comment by michaeldong** [comment]
how about this? @recover758126

**Comment by recover758126** [comment]
This problem cannot be reproduced temporarily, and more information can be provided, such as screenshots or screen recordings, etc. @michaeldong
