### ISSUE TITLE
rax-slider 无法配合 JSX+ 语法

### ISSUE THREAD

**Issue by muzea** [raxjs/rax-components#251]
如果用户这样写

```jsx
<Slider className="slider" width="750" height="500" autoPlay>
  <Slider.Item x-if={false}>
    <Fragment>
      <Image
        source={{
          height: '500rpx',
          width: '750rpx',
          uri: '//gw.alicdn.com/tfs/TB19NbqKFXXXXXLXVXXXXXXXXXX-750-500.png',
        }}
      />
    </Fragment>
  </Slider.Item>
  <Slider.Item>
    <Image
      source={{
        height: '500rpx',
        width: '750rpx',
        uri: '//gw.alicdn.com/tfs/TB1tWYBKFXXXXatXpXXXXXXXXXX-750-500.png',
      }}
    />
  </Slider.Item>
  <Slider.Item>
    <Image
      source={{
        height: '500rpx',
        width: '750rpx',
        uri: '//gw.alicdn.com/tfs/TB1SX_vKFXXXXbyXFXXXXXXXXXX-750-500.png',
      }}
    />
  </Slider.Item>
</Slider>
```

第一个为空的 `Slider.Item` 在 Web 上仍然会被渲染出来。

https://github.com/raxjs/rax-components/blob/bfffa4df9c279999838c932115724a812c11a096/packages/rax-slider/src/slider.web.tsx#L194-L215

https://github.com/jsx-plus/babel-runtime-jsx-plus/blob/946973a159c74dd44fccda412ed35f76d2282e70/src/createCondition.js#L25-L33

`createCondition` 会把条件为假的元素渲染为 `null`，但是 `slider` 并没有处理空的 child。

[demo 传送门](https://github.com/muzea-demo/rax-slider-jsxplus-bug/blob/master/src/index.tsx)

**Comment by SoloJiang** [comment]
@fyangstudio cc

**Comment by fyangstudio** [comment]
不要给 slider 设置空子节点。

**Comment by muzea** [comment]
这里只是指出 rax 的实现在 小程序/web 的处理表现不一致
如果这种基础的一致性都做不到，请不要称呼自己 "完整的多端生态"
