### ISSUE TITLE
Why rax-picture no longer supported. Use @ali/rax-picture instead?

### ISSUE THREAD

**Issue by Gaohaoyang** [raxjs/rax-components#328]
Why not support? I want to know the reason.

**Comment by chenjun1011** [comment]
rax-picture 所做的优化大多和提供图片服务的 CDN 强绑定，比如在图片上加上尺寸后缀、webp后缀等，都依赖图片服务是否支持这些能力。非 ali 的域下很难直接复用，所以被迁移到了 @ali/rax-picture

如果是内部用户 推荐用 @ali/rax-picture， 如果是外部场景，可以用 rax-image
