### ISSUE TITLE
Slider 不能自适应高度（小程序中）

### ISSUE THREAD

**Issue by Rabbitzzc** [raxjs/rax-components#355]
#### 问题
Slider 不能自适应高度（小程序中），好像是小程序 Swiper 内置组件就不支持，希望能支持一下。

#### 备注
而且看了源码，`Number(height)` 应该不合理，应该写成 `Number(height) || auto`

**Comment by SoloJiang** [comment]
小程序自身就不能自适应高度，所以这个无法支持

**Comment by Rabbitzzc** [comment]
嗯呢，看到了，通过小程序原生 swiper 支持的
