### ISSUE TITLE
请优化rax-scrollView的包大小

### ISSUE THREAD

**Issue by jiajiazhong** [raxjs/rax-components#395]
![image](https://user-images.githubusercontent.com/18545300/129547187-52fa999a-b83d-462c-81d5-2fff4186244f.png)
rax-scrollView单包一共打包进了weex、miniapp、web版本的代码，希望能做优化，这个包里面三分之二的代码一般都不需要使用

**Comment by SoloJiang** [comment]
已经内网回复过~
