### ISSUE TITLE
web 环境下缺少 scrollerRef.current 为 null 的判断，导致 js 报错

### ISSUE THREAD

**Issue by Matthew1994** [raxjs/rax-components#431]
以下是来自 arms 的报错
Uncaught TypeError: Cannot read property 'offsetHeight' of null

TypeError: Cannot read property 'offsetHeight' of null
at webpack:///node_modules/_rax-scrollview@3.7.1@rax-scrollview/es/web/index.js:191:22
at webpack:///node_modules/_rax-scrollview@3.7.1@rax-scrollview/es/throttle.js:11:10

----------------
希望加上 scrollerRef.current 不为 null 的判断
![image](https://user-images.githubusercontent.com/11374030/149880407-d3719aa3-7d9c-4dc4-8b88-5fefc3d1bb0e.png)

**Comment by fyangstudio** [comment]
麻烦提供下 问题的 Demo。

PS： 请不要操作不存在的节点。

**Comment by fyangstudio** [comment]
如果是概率性的，那么这个问题大概率是操作了不存在的节点。

可能的原因可能出在 https://github.com/raxjs/rax-components/blob/master/packages/rax-scrollview/src/web/index.tsx#L273
麻烦确认下 是否设置了 scrollEventThrottle ，这里节流延时触发时，可能是 节点不存在时触发的。

如果是上述原因 ，rax-scrollview 应该修改下，兼容此场景。   若不是，那么这个节点不存在的问题，不一定是 rax-scrollview 兼容了就能完全消除的（可能其他节点也会报错 组件不存在）

**Comment by Matthew1994** [comment]
使用中没有设置 scrollEventThrottle。还是需要 rax-scrollview 兼容一下，因为直接 js 报错了，会引起白屏或者跳到错误页面

**Comment by RaymondGsc** [comment]
遇到了同样的问题，未设置scrollEventThrottle，看报错逻辑确实是在ScrollView节点不存在时触发的~

**Comment by MrpandaLiu** [comment]
同存在此问题

**Comment by wssgcg1213** [comment]
Fixed at rax-scrollview@3.7.4
