### ISSUE TITLE
rax-modal 内的所有事件都被拦截了无法触发

### ISSUE THREAD

**Issue by yinhangfeng** [raxjs/rax-components#88]
这个 pr https://github.com/raxjs/rax-components/pull/80 导致所有事件都被拦截
modal 内无法触发 click，ScrollView 无法滚动
maskCanBeClick 属性也无效了...

**Comment by recover758126** [comment]
了解了，没有考虑到这个情况，会尽快修复

**Comment by doubleYoYo** [comment]
遇到同样问题，请问修复了吗？

**Comment by SoloJiang** [comment]
> 遇到同样问题，请问修复了吗？

本周修复
